apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: endormi2/vue-docker-image:latest
        ports:
        - containerPort: 80
